"""The functions of Moraff's World's WORLD.EXE that have been identified.

Keyed by address in the re-laid layout `../decomp/ghidra-scripts/relayout.py`
produces: `(name, one-line purpose)`.  `../decomp/rename_mw.py` substitutes the
names into the decompilation, and the purposes become the trailing comment on
each function's header line.

The reverse engineering has covered character creation (`../docs/ROLLER.md`),
the dungeon, the monsters and the spells (`../docs/DUNGEON.md`); the rest of
the 580 functions are still `FUN_`.
"""

KNOWN = {
    # ---- Borland C++ 3.x runtime (segment 1000).  `build.py` gives these their
    # signatures from `../decomp/ghidra-scripts/runtime.py`, so they already
    # carry the name in the decompilation; they are listed here for the catalog.
    "1000:0000": ("entry", "c0 startup: sets DS/SS, clears BSS, calls main"),
    "1000:0f28": ("pow", "libm pow(double, double)"),
    "1000:115b": ("ftol", "double -> long, through the 80x87 emulator"),
    "1000:11b4": ("clock_ticks", "BIOS tick count (INT 1Ah) less a baseline; the seed source"),
    "1000:12c8": ("N_LXMUL", "32-bit multiply helper: DX:AX * CX:BX"),
    "1000:1328": ("F_LDIV", "signed 32-bit divide (far entry, retf 8)"),
    "1000:132f": ("F_LUDIV", "unsigned 32-bit divide"),
    "1000:1337": ("F_LMOD", "signed 32-bit modulo"),
    "1000:133f": ("F_LUMOD", "unsigned 32-bit modulo"),
    "1000:13d6": ("N_LXLSH", "32-bit shift left by CL"),
    "1000:13f7": ("N_LXRSH", "32-bit arithmetic shift right by CL"),
    "1000:165e": ("lmul32", "32x32 multiply used by rand() and fread/fwrite"),
    "1000:1696": ("srand", "seed = value, high word 0"),
    "1000:16a7": ("rand", "seed = seed*0x015A4E35 + 1; return (seed>>16) & 0x7fff"),
    "1000:16fa": ("unlink", "libc (INT 21h AH=41h)"),
    "1000:182b": ("time", "libc time(): DOS date and time -> seconds"),
    "1000:18a4": ("toupper", "libc"),
    "1000:28b4": ("getch", "conio (INT 21h AH=07h)"),
    "1000:2aee": ("kbhit", "conio (INT 21h AH=0Bh)"),
    "1000:2c6c": ("malloc", "libc"),
    "1000:3306": ("sound", "PC speaker: 1193180 / hz into timer 2"),
    "1000:34d9": ("fclose", "libc"),
    "1000:3796": ("fopen", "libc"),
    "1000:38a2": ("fread", "libc"),
    "1000:3a79": ("fwrite", "libc"),
    "1000:3b5c": ("fgetc", "libc"),
    "1000:3c74": ("itoa", "libc"),
    "1000:3cb6": ("ltoa", "libc (long -> string)"),
    "1000:3f3b": ("fputc", "libc"),
    "1000:4432": ("strcat", "libc"),
    "1000:44d0": ("strcpy", "libc"),
    "1000:44f2": ("strlen", "libc"),

    # ---- WORLD module (segment 2000)
    "2000:03cb": ("quit", "back to text mode and exit"),
    "2000:1aca": ("shade_palette_banks", "eleven darkening copies of the first sixteen palette entries"),
    "2000:240c": ("load_h_bin", "reads H.BIN"),
    "2000:27b8": ("load_world_pic", "reads WORLD.PIC"),
    "2000:2d36": ("random_n", "reseeds from the clock, then returns rand() * n / 32768"),
    "2000:2d8e": ("recompute_weight", "the weight carried: coins, weapons and armour, plus the body unless feathered"),
    "2000:2ee7": ("store", "the general store menu"),
    "2000:342d": ("financial_statement", "the money breakdown screen"),
    "2000:35b1": ("inn", "the Flea Bag Inn"),
    "2000:3716": ("bank", "Moraff's First National Bank"),
    "2000:3ae1": ("set_map_view", "the map cell size and view extent: 0 the whole floor, 1 the scrolling view"),
    "2000:3c8f": ("select_player", "the ten save slots: name, sex, race, class per slot"),
    "2000:4043": ("game_disk_prompt", "the 360K one-character-per-disk notice"),
    "2000:412b": ("check_v_file", "prints and checksums the file V; the registration check"),
    "2000:4252": ("load_worldmap_bin", "reads WORLDMAP.BIN"),
    "2000:4292": ("main", "argv handling, video setup, then the slot/roll/play loop"),
    "2000:4538": ("monster_type_at", "the type of the monster standing on a square, or -1"),
    "2000:4575": ("occupant_at", "the monster index on a square of the occupancy grid, 0xff as -1"),
    "2000:45a1": ("set_occupant", "writes a monster index into the 80x110 occupancy grid"),
    "2000:45bd": ("pick_monster", "rolls a monster type the level and WORLD.PIC both allow"),
    "2000:46a4": ("generate_section", "stocks a floor with 145 monsters; never touches the map"),
    "2000:4fb4": ("save_mon_map", "writes <slot>MON.MAP: three levels, three monster lists"),
    "2000:507a": ("load_mon_map", "reads <slot>MON.MAP, or stocks the floor if it is missing"),
    "2000:51fd": ("is_explored", "bit test on the current floor's explored-squares bitmap"),
    "2000:5263": ("mark_explored", "sets a square's bit in the current floor's explored-squares bitmap"),
    "2000:5298": ("save_dun", "writes the <n>.DUN floor file"),
    "2000:542b": ("load_dun", "reads the <n>.DUN floor file"),
    "2000:55fc": ("enter_level", "switches floor: monsters, .DUN block and explored map"),
    "2000:5708": ("random_walk", "steps +/-1 while random(3) is non-zero; no callers"),
    "2000:575a": ("random_run", "the number of consecutive coin flips won, capped at n"),
    "2000:578c": ("roll_dice", "the sum of n rolls of random(d)"),
    "2000:57d7": ("load_dung_bin", "reads DUNG.BIN"),
    "2000:580e": ("load_player", "fread of the 0x928-byte record from slot file <n>"),
    "2000:58bf": ("save_player", "fwrite of the 0x928-byte record to slot file <n>"),
    "2000:590b": ("spells_hlp_probe", "opens SPELLS.HLP twice, drops both handles; no callers"),
    "2000:5938": ("load_spell_text", "SPELLS.HLP record n (0..119) into the spell text buffer"),
    "2000:59fd": ("experience_needed", "pow(1.36, level - 1) * 250 - 130, what a level takes"),
    "2000:5a42": ("experience_for_level", "the level thresholds"),
    "2000:5ae2": ("can_level_up", "true once the experience covers the next level"),
    "2000:5b41": ("level_from_experience", "the highest level the experience covers"),
    "2000:5bef": ("strike", "the player's attack on a monster"),
    "2000:603f": ("puffball_stat", "the puffball's stat drain/raise, by stat number"),
    "2000:615c": ("monster_turn", "the monster's attack, its breath and what a hit drains"),
    "2000:7756": ("drop_item", "the L key: drop a suit of armor, a weapon or a pile of coins"),
    "2000:7c2d": ("surface_feature", "the terrain 0..5 of a surface square, from its position"),
    "2000:7e4f": ("tick_spell_timers", "counts every spell timer down by the moves taken, undoing what expires"),
    "2000:81cd": ("monsters_move", "the monster movement pass, and the timers that run down with it"),
    "2000:8fd8": ("show_help", "prints <n>.HLP a page at a time, in the colours it names"),
    "2000:933a": ("view_stats", "the vital-statistics screen"),
    "2000:9d03": ("chute", "falling down a chute"),
    "2000:9e4a": ("chute_target", "the level a chute on this square drops to, or this one"),
    "2000:a19d": ("dig_hole", "digging through the floor"),
    "2000:a698": ("trapdoor_target", "the level a trap door on this square leads to, or -1"),
    "2000:aad5": ("movecontrol", "the main play loop: keys, movement, menus"),
    "2000:c28a": ("say_no_monster", "prints \"YOU ARE NOT CURRENTLY ENGAGING ANY MONSTER\""),
    "2000:c2b6": ("say_redundant", "prints \"CASTING THIS SPELL WOULD BE REDUNDANT\""),
    "2000:c2e2": ("say_already_cast", "prints \"YOU HAVE ALREADY CAST THIS SPELL\""),
    "2000:c30e": ("enchant_weapon", "the weapon-slot menu; sets the plus of the one picked to exactly n"),
    "2000:c3d5": ("enchant_armour", "the armour-slot menu; sets the plus of the one picked to exactly n"),
    "2000:c49c": ("raise_prep_armour", "the preparation armour bonus to n, refusing an n it already has"),
    "2000:c4be": ("raise_prep_weapon", "the preparation weapon bonus to n, refusing an n it already has"),
    "2000:c4e0": ("raise_body_armour", "the body armour level to n, refusing an n it already has"),
    "2000:c502": ("raise_ring_protection", "the ring of protection to n, refusing an n it already has"),
    "2000:c524": ("raise_ring_antimagic", "the anti-magic ring to n; only the inventory screen reads it back"),
    "2000:c546": ("cast_spell", "the spell menu"),
    "2000:c97a": ("say_feel_good", "prints \"YOU FEEL GOOD\""),
    "2000:c9a6": ("say_feel_very_good", "prints \"YOU FEEL VERY GOOD\""),
    "2000:c9d2": ("explosion", "the three explosion spells: 75-175, 125-225 or 200-500 off the monster"),
    "2000:caba": ("sleep_monster", "sleep for 10 monster turns when random(the monster's depth) is 0"),
    "2000:cb43": ("boost_strength", "+7 strength for 60 moves; refused while it is already running"),
    "2000:cb6d": ("boost_agility", "+7 agility for 60 moves; refused while it is already running"),
    "2000:cb97": ("boost_strength_and_agility", "60 moves on both timers, +7 only where one was not running"),
    "2000:cbdf": ("teleport_player", "moves the character to a random square that is neither rock nor taken"),
    "2000:cc66": ("spell_proof", "true for the kind-100 monster no battle spell touches"),
    "2000:cccc": ("teleport_monster", "moves the engaged monster to a random square that is not rock"),
    "2000:cdc5": ("autokill", "the brain-explosion roll, the character's against the monster's"),
    "2000:cedc": ("say_sixty_more_moves", "prints the \"NOW IT WILL LAST 60 MOVES LONGER\" notice"),
    "2000:cf08": ("raise_power_weapon", "power weapon level n for 60 moves; the same n adds 60 more"),
    "2000:cf6c": ("raise_protection", "protection level n for 60 moves; the same n adds 60 more"),
    "2000:cfd0": ("resist_poison", "60 more moves on the resist-poison timer"),
    "2000:d006": ("resist_disease", "60 more moves on the resist-disease timer"),
    "2000:d03c": ("anti_cold", "60 more moves on the anti-cold timer"),
    "2000:d072": ("anti_fire", "60 more moves on the anti-fire timer"),
    "2000:d0a8": ("resist_drain", "60 more moves on the resist-level-drain timer"),
    "2000:d0de": ("drain_monster", "takes wisdom off the monster's depth, and kills it outright below that"),
    "2000:d195": ("teleport_direction", "asks a direction and moves 2 to 19 squares that way, through walls"),
    "2000:d358": ("spell_effect", "the switch on category, level and slot that every spell arrives at"),
    "2000:ea27": ("spell_screen", "the spell, scroll, wand and paper menus: the class gate and the cost"),

    # ---- TOWN/CREATE module (segment 3000)
    "3000:0105": ("draw_picture", "draws a WORLD.PIC image scaled into a rectangle"),
    "3000:04d3": ("draw_wall_picture", "maps a WALL.PIC image across one face of the 3-D view"),
    "3000:4434": ("read_roll_line", "one line of ROLL.TXT into a buffer, dropping '|'"),
    "3000:4477": ("show_roll", "prints the six characteristics, height, weight, age and sex"),
    "3000:4695": ("roll_char", "character creation: race, stats, name, class, starting kit"),
    "3000:9a93": ("say_find_one_first", "prints \"DON'T YOU THINK YOU'D BETTER FIND ONE FIRST?\""),
    "3000:9ac0": ("take_pill", "one of the six vitamin pills: four onto one characteristic, two off another"),
    "3000:a384": ("myrand", "the dungeon hash over (x, y, level, dungeon); DotU's, exactly"),
    "3000:a449": ("ladder_delta", "how far a ladder here leads: + down, - up, 0 no ladder"),
    "3000:a524": ("wall_side", "the wall value 0..3 on one side of a square, from DUNG.BIN"),
    "3000:a5f7": ("draw_wall_side", "draws one wall of a map cell, door marks and all"),
    "3000:a854": ("is_solid", "true when all four sides of a square are walls"),
    "3000:a932": ("draw_cell_corners", "the four corner dots of a map cell at high zoom"),
    "3000:a97d": ("draw_map_square", "one automap cell: terrain, walls, ladder, trap door, chute"),
    "3000:af6f": ("seeded_pick", "chained srand/rand over (x, y, level, dungeon); no callers"),
    "3000:b7fd": ("load_spell_lines", "SPELLS.HLP record category*30 + level*3 + slot, split at '@' into lines"),
    "3000:b8d4": ("experience_for_kill", "(mult + 1) * (5 * 1.23^depth + depth + 1), depth capped at 130"),
    "3000:d51c": ("monster_killed", "the kill: experience, the drops, and a boss's flag and reward"),
    "3000:e221": ("use_magic_item", "the floor slosher, the potion, the two stones and the hand grenade"),

    # ---- DISP module (segment 4000)
    "4000:0a20": ("load_font", "reads .FNT file n into the three glyph buffers"),
    "4000:0b14": ("print_text", "one line of text at a scaled x,y in a colour"),
    "4000:0d0f": ("print_text_clipped", "print_text with a right-hand limit"),
    "4000:100f": ("load_palette", "hands the 768-byte palette buffer to the BIOS"),
    "4000:109d": ("palette_ramp", "the red and green ramp set_palette starts every entry from"),
    "4000:10ee": ("set_palette", "builds the floor's 256-colour palette and loads it"),
    "4000:2020": ("fill_rect", "fills a rectangle with a colour"),
    "4000:2ef7": ("mouse_pick", "which entry of a screen-region table the mouse is on"),
    "4000:34d8": ("clear_screen", "blanks the screen and hides the mouse cursor"),
    "4000:3452": ("wait_key", "waits for a key or a mouse button"),
    "4000:3532": ("flush_keys", "drains the keyboard and mouse buffers"),
    "4000:3db9": ("read_string", "types a string: uppercased, letters, digits and space"),
    "4000:42d2": ("format_two_numbers", "builds \"<a><n><b><m>\" in the scratch string"),
    "4000:4147": ("draw_text_box", "prints text into a cleared rectangle"),

    # ---- the 360x480 mode setup (segment 5110)
    "5110:009c": ("write_dac", "writes n palette entries to the VGA colour registers"),
}
