-- Nobody signs up. A player is a secret their device made and a name they picked, and only the
-- SHA-256 of the secret is here: the server can recognise a secret it is handed and cannot hand
-- one out, so a copy of this table is not a set of keys to anybody's runs.
CREATE TABLE players (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  secret_hash text NOT NULL UNIQUE,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Names are held without regard to case, so one player's name cannot be taken by another
-- spelling it differently. The index is on the folded name, so every lookup of a name has to fold
-- it too or it will not use the index (server/players.ts).
CREATE UNIQUE INDEX players_name ON players (lower(name));
