-- A run as it is played: the character, the sittings it has been played in, the stretches of keys
-- that arrived, and the verdict the replay gave at the end.
--
-- A character here is a roster entry in somebody's browser, and its id is that entry's, so the
-- first batch of a run is what makes it known and no registration step is needed. It belongs to
-- the player whose secret sent it and nobody else may send for it afterwards.
CREATE TABLE characters (
  id text PRIMARY KEY,
  player_id integer NOT NULL REFERENCES players(id),
  game text NOT NULL,
  mode text,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- When the run ended and how, which is a death or a win and nothing else: leaving the game is
  -- not an ending, since the character is played again from where it stood.
  finished_at timestamptz,
  outcome text
);

-- One sitting at the game. The seed, the engine and the record are what a replay starts from, and
-- the rest is what the site claims that sitting came to, rewritten by every batch so the newest
-- stands. A replay checks the claims; nothing here is believed on its own.
--
-- `started_at` is text because it is the site's own word for when the sitting began, kept as it
-- arrived and handed back the same way. The clock this server trusts is on the batches below.
--
-- `record` is the character as the sitting began, which is the bytes a replay starts the game
-- from; the site sends them written base64 and they are kept as the bytes they name.
CREATE TABLE sessions (
  character_id text NOT NULL REFERENCES characters(id),
  session_index integer NOT NULL,
  seed bigint NOT NULL,
  engine text NOT NULL,
  game text NOT NULL,
  leaderboard text,
  sound boolean,
  name text NOT NULL,
  started_at text NOT NULL,
  record bytea NOT NULL,
  mode text,
  actions integer NOT NULL,
  time double precision NOT NULL,
  edits integer NOT NULL,
  milestones jsonb NOT NULL,
  PRIMARY KEY (character_id, session_index)
);

-- One stretch of a sitting, as it arrived. `arrived_at` is the server's own clock in
-- milliseconds, and the gaps between consecutive stamps within a sitting are the run's play time:
-- the site sends every few seconds while the character is being played and stops when the game is
-- left, so a long gap is time the player was away.
--
-- The sequence is the site's count of the batches of that sitting, and it is what makes a resend
-- harmless: a batch whose sequence is already here arrived before and is not appended again.
CREATE TABLE batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id text NOT NULL REFERENCES characters(id),
  session_index integer NOT NULL,
  sequence integer NOT NULL,
  inputs jsonb NOT NULL,
  pressed integer NOT NULL,
  arrived_at bigint NOT NULL,
  ending boolean NOT NULL,
  UNIQUE (character_id, session_index, sequence)
);

-- What replaying the whole chain said, once the run has ended. `play_ms` and `timed` are read off
-- the batch stamps rather than out of the run, and `eligible` is whether the run may go on a
-- board at all.
CREATE TABLE verdicts (
  character_id text PRIMARY KEY REFERENCES characters(id),
  status text NOT NULL,
  reason text,
  actions integer NOT NULL,
  time double precision NOT NULL,
  milestones jsonb NOT NULL,
  play_ms bigint NOT NULL,
  timed boolean NOT NULL,
  eligible boolean NOT NULL,
  engine_commits jsonb NOT NULL,
  verified_at timestamptz NOT NULL DEFAULT now()
);
